@baseUrl = http://localhost:3333
@authToken = {{authenticate_user.response.body.access_token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Usuário Teste",
  "email": "teste@teste.com.br",
  "password": "123456"
}

###

# @name authenticate_user
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "email": "teste@teste.com.br",
  "password": "123456"
}

###

# @name create_meal
POST {{baseUrl}}/meals
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "034f3167-fa72-4b4e-bbd7-7cbce1ad4690",
  "name": "Refeição Teste 3",
  "description": "Apenas uma refeição de teste 3",
  "date": "2023-10-24T13:19:04.830Z",
  "isOnUserDiet": false
}