version: "3.8"

services:
  app:
    build:
      context: .
    container_name: daily-diet-api
    image: daily-diet-api
    ports:
      - '3333:3333'
    volumes:
      - ./:/app
    networks:
      - main
    depends_on:
      - database
  database:
    container_name: daily-diet-database
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: daily-diet-database
      PGDATA: /data/postgres
    networks:
      - main
    volumes:
      - ./data/pg:/data/postgres

networks:
  main: